### ISSUE TITLE
Implement some kind of workspace recipe / macros

### ISSUE THREAD

**Issue by Arkanosis** [binjr/binjr#97]
It would be awesome to have a way to automatically create tabs and graphs based on a source and hand-written recipe.

The recipe could be some YAML dialect with tree pattern matching, eg.:

```yaml
My tab name:
    My graph name:
        - /My host name/System/Load/CPU usage/*
    My other graph name@stacked:
        - /My host name/System/Processus/searchserver-*/Memory usage/Average size
        - /My host name/System/Processus/index6-*/Memory usage/Average size
    My other graph name:
        - ^/foo.*bar(hello|world)(/[^/]+)*$@regex
```

Keep in mind though that we'd probably want to expose all settings (such as line color, opacity…) through the recipe, so the actual YAML dialect might end up being much more complex than that.
